# Generated by Django 3.0.1 on 2019-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191227_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininfo',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='traininfo',
            name='short_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='traininfo',
            name='train_num',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
